In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/game-of-thrones-books/004ssb.txt
/kaggle/input/game-of-thrones-books/005ssb.txt
/kaggle/input/game-of-thrones-books/001ssb.txt
/kaggle/input/game-of-thrones-books/002ssb.txt
/kaggle/input/game-of-thrones-books/003ssb.txt


In [2]:
import gensim
import os

In [3]:
!pip install --upgrade gensim --user

In [4]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [5]:
story=[]
list=['/kaggle/input/game-of-thrones-books/004ssb.txt',
      '/kaggle/input/game-of-thrones-books/005ssb.txt',
      '/kaggle/input/game-of-thrones-books/001ssb.txt',
      '/kaggle/input/game-of-thrones-books/002ssb.txt',
      '/kaggle/input/game-of-thrones-books/003ssb.txt']
for item in list:
    f = open(item, encoding='utf-8', errors='ignore')
    corpus=f.read()
    raw_sent=sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [6]:
story

[['version',
  'history',
  'reedited',
  'by',
  'maelstrom',
  'feast',
  'for',
  'crows',
  'book',
  'four',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'george'],
 ['martin', 'prologue', 'dragons', 'said', 'mollander'],
 ['he',
  'snatched',
  'withered',
  'apple',
  'off',
  'the',
  'ground',
  'and',
  'tossed',
  'it',
  'hand',
  'to',
  'hand'],
 ['throw', 'the', 'apple', 'urged', 'alleras', 'the', 'sphinx'],
 ['he',
  'slipped',
  'an',
  'arrow',
  'from',
  'his',
  'quiver',
  'and',
  'nocked',
  'it',
  'to',
  'his',
  'bowstring'],
 ['should', 'like', 'to', 'see', 'dragon'],
 ['roone',
  'was',
  'the',
  'youngest',
  'of',
  'them',
  'chunky',
  'boy',
  'still',
  'two',
  'years',
  'shy',
  'of',
  'manhood'],
 ['should', 'like', 'that', 'very', 'much'],
 ['and',
  'should',
  'like',
  'to',
  'sleep',
  'with',
  'roseys',
  'arms',
  'around',
  'me',
  'pate',
  'thought'],
 ['he', 'shifted', 'restlessly', 'on', 'the', 'bench'],
 ['by', 'the', 'morrow

In [7]:
len(story)

158872

In [8]:
story[4]

['he',
 'slipped',
 'an',
 'arrow',
 'from',
 'his',
 'quiver',
 'and',
 'nocked',
 'it',
 'to',
 'his',
 'bowstring']

**Creating the Word2Vec model**

In [9]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4
)

In [10]:
model.build_vocab(story)


**Training**

In [11]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6575095, 8625265)

In [12]:
vec = model.wv.get_normed_vectors()
vec

array([[ 0.11527406, -0.13460705, -0.00741865, ..., -0.20418167,
        -0.02269617,  0.14081106],
       [-0.00958903, -0.01333461,  0.02226652, ..., -0.04734587,
        -0.05782534,  0.1088709 ],
       [ 0.01436773,  0.13652745, -0.03851957, ...,  0.0291325 ,
         0.24270934, -0.10698295],
       ...,
       [-0.09654476,  0.13041385,  0.03326552, ..., -0.05890206,
        -0.04529595,  0.00394327],
       [ 0.07769376,  0.17889357,  0.03125156, ...,  0.14703661,
        -0.02877178, -0.0908158 ],
       [ 0.04589675,  0.0971758 , -0.02376644, ..., -0.00609999,
        -0.02946034,  0.09110641]], dtype=float32)

In [13]:
len(vec[0])

100

**Most similar words to 'daenerys'**

In [14]:
model.wv.most_similar('lannister')

[('house', 0.7145041227340698),
 ('tully', 0.6913048624992371),
 ('kingsguard', 0.678695797920227),
 ('sworn', 0.6758788824081421),
 ('heir', 0.6756640672683716),
 ('twin', 0.6633954644203186),
 ('baratheon', 0.6623036861419678),
 ('declared', 0.6589474081993103),
 ('highgarden', 0.6562409996986389),
 ('captive', 0.6548166871070862)]

**Vector representation of daenerys**

In [15]:
model.wv['lannister']

array([ 5.91758013e-01, -1.21959887e-01,  2.08880806e+00, -2.33295751e+00,
       -1.13767004e+00,  1.26949656e+00, -1.73590168e-01, -6.51467502e-01,
       -6.64835691e-01,  6.13274515e-01, -1.29096115e+00, -4.96812850e-01,
        8.62447381e-01,  1.14132881e+00, -1.69719005e+00, -1.94442546e+00,
       -5.24128973e-01, -8.51204991e-01, -2.81582046e+00, -9.76475537e-01,
       -2.26145133e-01, -3.86500835e-01, -8.32441688e-01, -1.12416863e+00,
        6.46644056e-01, -1.98558211e+00, -2.54712164e-01,  1.66943479e+00,
        8.67543817e-01,  1.45216477e+00, -5.81745207e-01, -5.16770244e-01,
       -2.24564886e+00, -2.10872218e-01, -9.09275949e-01, -2.24156722e-01,
        1.66777813e+00, -2.34084821e+00,  6.33881748e-01, -4.54533041e-01,
        1.83734596e-01,  6.81861520e-01,  1.64455295e+00, -2.08538222e+00,
        8.61133873e-01, -1.96857953e+00,  4.95214790e-01,  2.01533484e+00,
       -3.93318497e-02,  3.44226569e-01,  1.69620337e-03, -3.94081086e-01,
       -8.15464854e-02, -

**Similarities between two words/character**

In [16]:
model.wv.similarity('lannister','sansa')

-0.06623336

In [17]:
model.wv.similarity('lannister','daenerys')

0.39045766

**All the vector representation**

In [18]:
model.wv.get_normed_vectors()

array([[ 0.11527406, -0.13460705, -0.00741865, ..., -0.20418167,
        -0.02269617,  0.14081106],
       [-0.00958903, -0.01333461,  0.02226652, ..., -0.04734587,
        -0.05782534,  0.1088709 ],
       [ 0.01436773,  0.13652745, -0.03851957, ...,  0.0291325 ,
         0.24270934, -0.10698295],
       ...,
       [-0.09654476,  0.13041385,  0.03326552, ..., -0.05890206,
        -0.04529595,  0.00394327],
       [ 0.07769376,  0.17889357,  0.03125156, ...,  0.14703661,
        -0.02877178, -0.0908158 ],
       [ 0.04589675,  0.0971758 , -0.02376644, ..., -0.00609999,
        -0.02946034,  0.09110641]], dtype=float32)

In [19]:
model.wv.get_normed_vectors().shape

(17869, 100)

**Corresponding words from vector representation**

In [20]:
y=model.wv.index_to_key
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'them',
 'lord',
 'no',
 'from',
 'were',
 'would',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'could',
 'are',
 'we',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'king',
 'who',
 'well',
 'down',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'old',
 'hand',
 'even',
 'too',
 'before',
 'never',
 'tyrion',
 'an',
 'off',
 'know',
 'see',
 'into',
 'made',
 'father',
 'now',
 'eyes',
 'black',
 'told',
 'thought',
 'lady',
 'time',
 'then',
 'how',
 'long',
 'has',
 'might',
 'us',
 'come',
 'where',
 'here',
 'can',
 'through',
 'still',
 'face',
 'head',
 'red',
 'way',
 'page',
 'boy',
 'must',
 'once',
 'good',
 'two',
 'over',
 'little',
 'about',
 'brother'

In [21]:
len(y)

17869

## **Dimensionality Reduction using PCA**

In [22]:
from sklearn.decomposition import PCA

In [23]:
pca = PCA(n_components=3)

In [24]:
X=pca.fit_transform(model.wv.get_normed_vectors())

In [25]:
X

array([[-0.22018959,  0.56656045, -0.03216779],
       [-0.20006041,  0.33999714,  0.05819171],
       [ 0.24825367,  0.57590777,  0.24609493],
       ...,
       [ 0.0622356 , -0.26011842, -0.05157334],
       [ 0.5157213 ,  0.11071984,  0.00584122],
       [ 0.23144509, -0.08204066, -0.31912628]], dtype=float32)

In [26]:
len(X[0])

3

Dimension reduced to 3 from 100


In [27]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()